### ISSUE TITLE
Config resets on start

### ISSUE THREAD

**Issue by djohts** [Luluno01/BungeeGuard#10]
Config resets on every start, I can't edit any of the messages, please fix ASAP

**Comment by Luluno01** [comment]
I tested locally and I couldn't reproduce your problem. Did you reload the config via `/bsg reload` after you changed the message? 

It is highly possible that when you stop the server, BungeeSafeguard saves the in-memory config onto the file system, which could be an "old" config if you forgot to reload your latest config into memory. If you did reload, then there must be something prevented BungeeSafeguard from loading the correct config into the memory. In that case, you should have seen an error message when reloading, or you must have broke the config file (e.g., wrong YML syntax, mistype "whitelist-message" as "witelist-message" or whatever unrecognized config names).
