### ISSUE TITLE
似乎和 LibertyBans 不兼容...  / Can not be used together with LibertyBans...

### ISSUE THREAD

**Issue by MagmaBlock** [Luluno01/BungeeGuard#13]
使用 Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:866a450:468，比较新的版本 
俩插件也都是最新，当安装 [LibertyBans](https://www.spigotmc.org/resources/libertybans.81063/) 之后，BungeeSafeguard 的白名单功能会自动关闭
但是找不到报错或提示，这是因为两个插件共用了某个不能共用的API吗？
我还可能把这两款插件装在一起吗?

For English users:
_Under Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:866a450:468, almost the latest version_
_Both plugins are also latest. After [LibertyBans](https://www.spigotmc.org/resources/libertybans.81063/) is installed, the white list function of BungeeSafeguard will be automatically turned off_
_But there is no error report found. Is this because two plugins are using one same API?_
_Is it still possible to install them together?_

**Comment by Luluno01** [comment]
你好，可以描述一下具体的触发条件和行为吗？例如，是否仅1.18版本的Waterfall会出现这个问题？此外，“白名单功能自动关闭”是从何得到的信息？是执行`/bsg status`时提示白名单已关闭，还是`/bsg status`提示白名单启用，但`/wlist list`显示白名单为空，又或者是`/bsg status`和`/wlist list`均正常，但白名单功能不正常？如果是”白名单功能不正常”，请问具体的行为是什么？例如，是否放行了不该放行的玩家，或者禁止了白名单玩家进入（控制台会有输出提示该玩家被禁止加入服务器）？

**Comment by MagmaBlock** [comment]
抱歉，我又测试了下，但是惊讶的发现两个插件又没有问题了...

当时的情况是，加了 LibertyBans 插件后一星期，才发现没有白名单的人也能进入了
我排查了半天，发现 BungeeSafeguard config 里面的 `enable-whitelist: true`，莫名其妙变成了 `enable-whitelist: false`。
我改为 `true`，重载插件，却发现又被自动地改成了`false`..
尝试关闭BC后改，打开 `true`又变成了`false`...

这个应该是真的关闭了白名单，我当时看 `/bsg status` 当中白名单是关闭，除了黑名单的玩家之外都能进入
_（那个状态下lazy-whitelist仍然工作，不过它可能本来就不受开关影响x，list也是正常的）_
控制台没有找到任何相关的提示或报错，看起来一切正常

也许可以排查下插件主动关闭 `enable-whitelist` 情况的代码？十分抱歉，这会的确复现不出来了，如果又出现了我会再提供信息

**Comment by Luluno01** [comment]
插件不会主动关闭白名单，除非是你忘了reload了。有很大的可能应该是你改了config.yml，把`enable-whitelist: false`改成了`enable-whitelist: true`，但是没有reload，所以插件内存里还是保留着旧的配置，即`enable-whitelist: false`，当你通过插件修改黑白名单时，插件就会将内存中的配置一起重新保存到配置文件中。因此在你看来就会好像是插件自动关闭了白名单，实则是白名单从一开始就没有打开过。

修改配置文件后要记得reload才会把修改后的配置载入到内存里生效，或者你也可以通过`/wlist on`直接通过插件开启白名单，这样就能保证内存里的白名单设置一定是打开的。

如果确认是忘了reload导致的问题，没有其它可疑的问题的话就可以关闭这个issue了哦。之后如再遇到类似问题的话请留意配置文件与`/bsg status`的输出是否一致，不一致的话说明你大概率忘了reload；如果发现确实reload后仍有问题，可以reopen这个issue。

**Comment by MagmaBlock** [comment]
感谢解答！挺奇怪的，我记得当时我还重启过几次Bungee
不过现在看起来两个插件工作的也挺好，issue可能发的着急了点
如果再遇到我会再仔细看一看，感谢
