### ISSUE TITLE
Permission Nodes

### ISSUE THREAD

**Issue by 4o66** [Luluno01/BungeeGuard#2]
From the README.md, in migration instructions:
"4. Update assigned permissions, change bungeeguard to bungeesafeguard in permission nodes"

Is there a list of all the permissions nodes somewhere? I looked throught the source and found these:
```
bungeesafeguard.blacklist
bungeesafeguard.whitelist
bungeesafeguard.main
```

Did I miss any, and did I miss them in the documentation somewhere?

Thanks!

**Comment by Luluno01** [comment]
Smart you ahhhha. I did forget to list these permission nodes in README. The listed three permissions are the only permissions. I will add them later. However, their names are quite self-explaining. If you are smart enough you don't need to wait for my documentation :P

**Comment by Luluno01** [comment]
Okay, finally got my IDEA license renewed and document updated. Checkout the [Permission Nodes](../#permission-nodes) section.

**Comment by Luluno01** [comment]
If your have no further confusion on "permission nodes", you can close this issue. Thanks a lot ;P

**Comment by 4o66** [comment]
Thanks!
