### ISSUE TITLE
On trying to whitelist a username that doesn't exist, a java exception is thrown.

### ISSUE THREAD

**Issue by troykay** [Luluno01/BungeeGuard#3]
Hey there, 

When I try to add a whitelist entry (I'm assuming it happens with blacklist entries too?) using a username that doesn't exist (for example, if I make a typo), a java exception is thrown: 

22.05 08:41:51 [Server] WARN [BungeeSafeguard]: Failed to whitelist boogerbooger:
22.05 08:41:51 [Server] ERROR java.io.IOException: Invalid response
22.05 08:41:51 [Server] ERROR at vip.untitled.bungeesafeguard.helpers.UserUUIDHelper$getUUIDFromUsername$1.run(UserUUIDHelper.kt:19)
22.05 08:41:51 [Server] ERROR at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
22.05 08:41:51 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22.05 08:41:51 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22.05 08:41:51 [Server] ERROR at java.lang.Thread.run(Thread.java:748)

The error seems to be passed along to the user who issued the command: 

"failed to whitelist <username>: java.io.IOException:Invalid response"

It looks like the error either isn't caught, or a better message could be passed to the user:

"Failed to whitelist <username>: No such user."

(Thanks for the plugin btw! )

**Comment by Luluno01** [comment]
The failure is cause by not being able to parse the response properly - it is either user not found or some other unknown error, e.g. being rate limited. I was too lazy to identify type of the error, so I just tell the user the operation cannot be done and print the error for debugging purpose (it was not an uncaught exception). I am now looking for a way to identify the "Not Found" error, which is indicated by a weird status `204`. Hopefully a better message can be delivered in next release. Thank you ;P

**Comment by troykay** [comment]
I figured the ambiguity in response from the server was the case.

Thanks for thinking about it :D

**Comment by Luluno01** [comment]
> I figured the ambiguity in response from the server was the case.
> 
> Thanks for thinking about it :D

Yeah, exactly. Thank you for your nice translation ahha

**Comment by Luluno01** [comment]
Done. Checkout [v2.1](../releases/tag/v2.1).

**Comment by Luluno01** [comment]
I can't edit my reply on [www.spigotmc.org](https://www.spigotmc.org). For the second issue you mentioned, did you grant the player with appropriate permissions? (See [Permission Nodes](../#permission-nodes))
