### ISSUE TITLE
非白名单用户入服问题

### ISSUE THREAD

**Issue by KevinSun2004** [Luluno01/BungeeGuard#4]
非白名单用户加入服务器时游戏内会有提示，会瞬间出现
XXX 加入服务器
XXX 退出服务器
希望能进行修复

**Comment by Luluno01** [comment]
因为现在是靠踢出用户实现的禁止用户进入，之前我记得BungeeCord没有提供在用户正式加入前就踢掉他的API，我再去看看有没有这个API，没有的话我也没办法

**Comment by Luluno01** [comment]
Fixed by 88e6c3a080d6fc1aa12e44c8a7ecc021941bb6e2

**Comment by Luluno01** [comment]
你再测试一下，应该没问题了

**Comment by Luluno01** [comment]
For non-Chinese users, here is the description of this issue:

In older versions, BungeeSafeguard blocks players by kicking them. However, blocked player will still have a chance to join the backend server before being kicked. By handling player login event earlier in BungeeCord's life cycle, blocked players will be kicked without any chance to join the server.
