### ISSUE TITLE
Request: Is it possible to add a quick import of whitelist.json into this plugin?

### ISSUE THREAD

**Issue by vc606** [Luluno01/BungeeGuard#7]
My whitelist file Since the server has been open for a long time and accumulated a lot of player lists, 
I hope there is a way to quickly import whitelist.json.

**Comment by Luluno01** [comment]
I don't have much time recently, but your request is quite easy to solve if you know how to use multiline edit mode of VSCode (or any other advanced editor).

Well, you have the following choices:

1. Wait for me until I have done my on going work.
2. Use VSCode (or any other editor that supports multiline editing) to copy your existing whitelisted UUIDs into `config.yml` of BungeeSafeguard.
3. Send you old `whitelist.json` and `config.yml` to me and I will do it for you.

**Comment by Luluno01** [comment]
Implemented in [v2.5](https://github.com/Luluno01/BungeeSafeguard/releases/tag/v2.5). Please remember to backup your configurations before importing.
