### ISSUE TITLE
show username in dump command

### ISSUE THREAD

**Issue by MrGeorgen** [Luluno01/BungeeGuard#8]
could you add a command that shows all that are on the list?
like the vanilla `whitelist list` command
Edit: I did not notice the dump command. It could be imporved by showing the
coresspeonding username to the uuid

**Comment by Luluno01** [comment]
As the official UUID <=> username translation API has a rate limit, it's not recommended to show their latest usernames. However, what I can do is to show the "last known" usernames - which is the same functionality as the "player cache" of vanilla server. If this meets your need, then I would consider implementing it. Anything beyond this is not likely to be added to save time and reduce the complexity of this plugin - in which case, however, I would suggest to implement a dedicated username tracking and management service.

**Comment by Luluno01** [comment]
Implemented in v2.6.

**Comment by MrGeorgen** [comment]
> As the official UUID <=> username translation API has a rate limit, it's not recommended to show their latest usernames. However, what I can do is to show the "last known" usernames - which is the same functionality as the "player cache" of vanilla server. If this meets your need, then I would consider implementing it. Anything beyond this is not likely to be added to save time and reduce the complexity of this plugin - in which case, however, I would suggest to implement a dedicated username tracking and management service.

yeah this is perfectly fine because usernames don't change often anyway. Thank you
